# Configurazione Database
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=giorgia
spring.datasource.driver-class-name=org.postgresql.Driver

# Strategia di Hibernate: "update" aggiorna le tabelle in automatico se modifichi il codice Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true